### ISSUE TITLE
test/remote/device_tests.js failure (v1.50.0 and master)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1123]
Don't know why travis says this passes; it fails locally

STR
1. pull fxa-auth-db-mysql v0.50.0, npm install, npm start
2. In another shell, pull fxa-auth-server v1.50.0, npm install and then
    NODE_ENV=dev CORS_ORIGIN=http://foo/ ./scripts/tap-coverage.js test/remote/device_tests.js 2>/dev/null

Tests fail at the end on /account/devices, with this in the log:

```
stack":"Error: \"value\" at position 0 fails because [child \"name\" fails because [\"name\" must be a string]]
    at Object.exports.create (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/node_modules/boom/lib/index.js:254:92)
    at Object.exports.badImplementation (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/node_modules/boom/lib/index.js:290:23)
    at postValidate (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/lib/validation.js:194:26)
    at internals.Any._validateWithOptions (/Users/jrgm/tmp33/fxa-auth-server/node_modules/joi/lib/any.js:657:16)
    at root.validate (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/node_modules/joi/lib/index.js:102:23)
    at exports.response (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/lib/validation.js:213:20)
    at /Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/lib/request.js:370:13
    at iterate (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /Users/jrgm/tmp33/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:841:22
    at process._tickDomainCallback (node.js:492:13)"}}
```

Seems to the Joi check for a name on the response.

**Comment by philbooth** [comment]
Just to clarify something ahead of the pull request for this:

The error messages for `v1.50.0` and `master` are closely related but slightly different (at least when I run them). The tag complains that `name` is invalid, whereas `master` complains that `pushCallback` is invalid.

In both cases, the root cause is the same. I failed to RTFM, which states that `optional()` only permits values to be `undefined`, it rejects when they are `null`.
