### ISSUE TITLE
[train-58] /v1/recovery_email/status throws 500 on pre-existing dotless email addresses

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1219]
Unexpected echo effect of validation changes, but when I put 58 live, there were a bunch of 500 errors on route /v1/recovery_email/status. I immediately rolled back and everything is fine now on previous stack/release. When I matched the uid on the errors to emails in the database already, they all were typoed dotless addresses. (And clients are still polling for them, which is ugly, but).
Anyways, not going to ship 58, and we can look at how to deal with this for the coming train.
```
"stack":"Error: child \"email\" fails because [[object Object]]                                                                             
    at Object.exports.create (/data/fxa-auth-server/node_modules/hapi/node_modules/boom/lib/index.js:21:17)                                 
    at Object.exports.internal (/data/fxa-auth-server/node_modules/hapi/node_modules/boom/lib/index.js:254:92)                              
    at Object.exports.badImplementation (/data/fxa-auth-server/node_modules/hapi/node_modules/boom/lib/index.js:290:23)                     
    at postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:194:26)                                                      
    at internals.Any._validateWithOptions (/data/fxa-auth-server/node_modules/hapi/node_modules/joi/lib/any.js:645:16)                      
    at root.validate (/data/fxa-auth-server/node_modules/hapi/node_modules/joi/lib/index.js:102:23)                                         
    at exports.response (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:213:20)                                                  
    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:370:13                                                                        
    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:35:13)                                              
    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:27:25)                                                 
    at /data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:841:22                                                        
    at process._tickDomainCallback (node.js:492:13)"}}
```

**Comment by rfk** [comment]
I had a quick look, and this is the only endpoint that uses Joi validation on an "email" field in the response.  A quick fix could be to add code to this route that checks the email address, and deletes the known-to-be-defunct account if the address is invalid.
