### ISSUE TITLE
Reenable push e2e tests

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1368]
There is a problem where push returns status 410 instead of 201 for some subscriptions.
Need to investigate that

```
[13:53:50]  <vladikoff>	jrconlin, I'm running our e2e push tests and getting inconsistent responses like this: https://gist.github.com/vladikoff/eab910a3721c46308b9f94151c48b4a3
[13:55:10]  <vladikoff>	jrconlin, this uses the same channel id, with new subscriptions https://github.com/mozilla/fxa-auth-server/blob/master/test/e2e/push_tests.js#L34 (same public and auth key though)
[13:55:46]  <jrconlin>	vladikoff: are each of those using new subscriptions? In other words, are you requesting a new endpoint, getting it back and then getting a 410 response off of it immediately?
[13:56:07]  <vladikoff>	jrconlin, "are each of those using new subscriptions?" ->yes
[13:56:18]  <jrconlin>	hrm.
[13:57:01]  <vladikoff>	jrconlin, gonna try to set a pause after i get a subscription 
[13:57:02]  <jrconlin>	wonder if there might be a delay in dynamodb. 
[14:06:33]  <jrconlin>	vladikoff: Can you also print the URL if you get a 410 back?
[14:06:47]  <vladikoff>	jrconlin, sure, sec
[14:08:15]  <vladikoff>	jrconlin, adding a 5 or 20 sec delay doesn't help
[14:08:21]  <jrconlin>	Also, a bit confused by that test code. You're hardcoding the channelid (ok) and keys (also, ok) but you're using the server provided. "id" is something for your side, it's not the UAID, right?
[14:09:27]  <vladikoff>	jrconlin, with URLS https://gist.github.com/vladikoff/fe6aed82c90abf24995071f455a2b168
[14:10:15]  <vladikoff>	jrconlin, the 'id' is a device id, not used in Push
[14:10:20]  <jrconlin>	ok, good.
[14:22:34]  <vladikoff>	jrconlin, i reverted to an older version of the test that didn't use the crypto / payload bits, and that one worked properly.
[14:23:00]  <vladikoff>	jrconlin, but the new stuff with keys seems to be throwing 410 sometimes
[14:23:43]  <jrconlin>	huh, odd.
[14:41:02]  <jrconlin>	vladikoff: Are you hitting prod or stage? 
[14:41:09]  <vladikoff>	jrconlin, prod
[14:41:11]  <jrconlin>	ok
[14:41:23]  <vladikoff>	jrconlin, i can try stage, url?
[14:41:37]  <jrconlin>	No difference right now. We  just pushed
[14:42:49]  <jrconlin>	What looks like is happening is that you're fetching the endpoint, and then the endpoint is being immediately unsubscribed. 
[14:43:14]  <jrconlin>	You're kind of using a non-standard method to call the API, so we're trying to figure out how that's happening.
```

**Comment by vladikoff** [comment]
@kitcambridge could you please check this out when you have a moment:

If you check out this branch and `npm install`: https://github.com/mozilla/fxa-auth-server/tree/e2e-fail

then run:

```
 ./test/e2e/a.sh | grep "Got"
```

You will get inconsistent results from the push server, either a 410 or 200. 

```
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: 200
Got: 200
Got: 200
Got: 200
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
```

**Comment by vladikoff** [comment]
Commit link: https://github.com/mozilla/fxa-auth-server/commit/b836d4f30d7d08bd1b38776f22ba2a7d75145626

**Comment by vladikoff** [comment]
cc @kitcambridge

**Comment by kitcambridge** [comment]
Oops, I'm so sorry I missed this! I'll take a look in a bit.

**Comment by vladikoff** [comment]
ping  @kitcambridge

**Comment by rfk** [comment]
> If you check out this branch and npm install: https://github.com/mozilla/fxa-auth-server/tree/e2e-fail
> then run:
>   `./test/e2e/a.sh | grep "Got"`
> You will get inconsistent results from the push server, either a 410 or 200. 

I just retried this and couldn't reproduce, all the runs of the test seemed to go through successfully for me.  Perhaps it's been resolved on the push-server side?

**Comment by rfk** [comment]
@vladikoff could you please try to repro whenever you get a chance?

**Comment by vladikoff** [comment]
@rfk I still got:

```
➜  fxa-auth-server git:(e2e-fail)  ./test/e2e/a.sh | grep "Got"
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: 200
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)
Got: 200
Got: { [WebPushError: Received unexpected response code]
Unhandled rejection TypeError: db.updateDevice is not a function
    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:342:27
    at process._tickCallback (node.js:369:9)

```

so like half 200s and others are 400s

**Comment by rfk** [comment]
Thanks; maybe I'm running it wrong, will try again

**Comment by rfk** [comment]
For whatever reason, I found this easier to repro on my US-based VPS than on my home machine.  Possibly red-herring since as you noted above, it doesn't *seem* to be timing related.

**Comment by rfk** [comment]
The full response body on the failing requests appears to be:

```
{"errno": 103, "message": "Request did not validate UAID not found", "code": 410, "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "error": ""}
```

**Comment by rfk** [comment]
I'm starting to thing this actually is a timing issue, but in the websocket registration handshake rather than in the sending of the message to the push endpoint.  I tried refactoring the handshake into a more explicit, sequential state-machine, and it seems to be running without errors.  I'll leave it running for a while longer and report back.
