### ISSUE TITLE
tests failing with a crash on auth-server (in auth-mailer code) on latest.dev

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1446]
Whoops. Auth-server now has no config.signInUrl, which is what is passed to fxa-auth-mailer to use, when used as a dependency. 

/cc @rfk 

```
"stack":"TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at Mailer._generateUTMLink (/data/fxa-auth-server/node_modules/fxa-auth-mailer/mailer.js:555:26)
    at Mailer.createSignInLink (/data/fxa-auth-server/node_modules/fxa-auth-mailer/mailer.js:628:17)
    at Mailer._generateLinks (/data/fxa-auth-server/node_modules/fxa-auth-mailer/mailer.js:595:31)
    at Mailer.verifyEmail (/data/fxa-auth-server/node_modules/fxa-auth-mailer/mailer.js:240:22)
    at Mailer.mailer.sendVerifyCode (/data/fxa-auth-server/lib/mailer.js:22:33)
    at sendVerifyCode (/data/fxa-auth-server/lib/routes/account.js:248:20)
    at b (domain.js:184:18)
    at tryCatcher (/data/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/data/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/data/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/data/fxa-auth-server/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/data/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/data/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:502:13)"}}
```

**Comment by jrgm** [comment]
Hmm. Auth server is ac124d8c3e46b39dad1698f8502a619b425d1aca (current HEAD of master), which should run auth-mailer b455d7491ce9b2e6826d6581cbca3d012819689c, and I had tried to force npm to rebuild everything (a trick that usually works too). 

Anyways, I'm going to blow away /data/fxa-auth-server so it definitely rebuilds everything, and see how that looks.

**Comment by jrgm** [comment]
Well this run is looking better...

**Comment by jrgm** [comment]
4 or so failing tests, so closing this one.
