### ISSUE TITLE
vapid key creation only created on mysql start?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1502]
I did a fresh install of fxa-local-dev on a linux box, when I went to start the servers the auth-server kept stopping. Looking at the logs, I see this error:

```
auth-server key server PORT 9000-2 (err): fxa-auth-server.CRITICAL: undefined Error: Cannot find module '/home/shane/development/fxa-local-dev/fxa-auth-server/config/vapid-keys.json'
auth-server key server PORT 9000-2 (err):     at Function.Module._resolveFilename (module.js:325:15)
auth-server key server PORT 9000-2 (err):     at Function.Module._load (module.js:276:25)
auth-server key server PORT 9000-2 (err):     at Function._load (/home/shane/development/fxa-local-dev/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
auth-server key server PORT 9000-2 (err):     at Module.require (module.js:353:17)
auth-server key server PORT 9000-2 (err):     at require (internal/module.js:12:17)
auth-server key server PORT 9000-2 (err):     at module.exports (/home/shane/development/fxa-local-dev/fxa-auth-server/lib/push.js:92:21)
auth-server key server PORT 9000-2 (err):     at module.exports (/home/shane/development/fxa-local-dev/fxa-auth-server/lib/routes/index.js:28:32)
auth-server key server PORT 9000-2 (err):     at DB.connect.done.log.error.op (/home/shane/development/fxa-local-dev/fxa-auth-server/bin/key_server.js:102:52)
auth-server key server PORT 9000-2 (err):     at tryCatcher (/home/shane/development/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)
auth-server key server PORT 9000-2 (err):     at Promise._settlePromiseFromHandler (/home/shane/development/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)
auth-server key server PORT 9000-2 (err):     at Promise._settlePromiseAt (/home/shane/development/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)
auth-server key server PORT 9000-2 (err):     at Promise._settlePromises (/home/shane/development/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:697:14)
auth-server key server PORT 9000-2 (err):     at Async._drainQueue (/home/shane/development/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:123:16)
auth-server key server PORT 9000-2 (err):     at Async._drainQueues (/home/shane/development/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)
auth-server key server PORT 9000-2 (err):     at Immediate.Async.drainQueues [as _onImmediate] (/home/shane/development/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)
auth-server key server PORT 9000-2 (err):     at processImmediate [as _immediateCallback] (timers.js:383:17)

[PM2] Streaming realtime logs for [2] process 

```

@vbudhram helped me by pointing me to https://github.com/mozilla/fxa-auth-server/blob/6e6b28c7a146ecfdcf9c134a7ebb6e76c34f2195/scripts/start-local-mysql.sh#L6.

If we use the in memory server, creating the keys from start-local-mysql doesn't generate the keys?

**Comment by rfk** [comment]
They're also created by start-local.sh:

  https://github.com/mozilla/fxa-auth-server/blob/6e6b28c7a146ecfdcf9c134a7ebb6e76c34f2195/scripts/start-local.sh#L6

But it looks like fxa-local-dev doesn't use either of those scripts, and just calls `./bin/key_server.js` directly.

Perhaps I should have either (a) created these keys as part of the existing gen_keys.js script, or (b) preffed them off by default, so you can start the server without keys present.
