### ISSUE TITLE
prod 500 errors on account/devices/notify for Fx51+

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1510]
Noticed we're getting some 500's in prod like this:
```
"path":"/v1/account/devices/notify"
"agent":"Firefox-Android-FxAccounts/51.0a2 (Firefox)"
"stack":"Error: \"value\" must be an object
    at postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:201:26)
    at _validateWithOptions (/data/fxa-auth-server/node_modules/joi/lib/any.js:604:20)
    at root.validate (/data/fxa-auth-server/node_modules/joi/lib/index.js:105:23)
    at internals.input.exports.response.postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:221:20)
    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)
    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)
    at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16
    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:86:16)
    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at internals.Response._prepare.internals.Response._processPrepare.next [as _processPrepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:521:16)
    at internals.Response._prepare.next [as _prepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:460:21)
    at /data/fxa-auth-server/node_modules/hapi/lib/reply.js:152:22
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)"}}
```

**Comment by rfk** [comment]
(From the private thread):

@rfk:
"""
Looks like an error in constructing the response payload. Perhaps android is sending a badly-formed message, and we're trying to report an error, but the error-rendering itself is not working quite right.
"""

@seanmonstar:
"""
When I looked into that route, I was first surprised at there being a couple throws in non-Promise code. I thought we also caught the errors in Promise context and fed the error into reply, but I suppose it works that way also?
"""

**Comment by philbooth** [comment]
@rfk, @seanmonstar can you triage?

**Comment by jrgm** [comment]
Seeing more of these. Problem with `Firefox-Android-FxAccounts/{51.0a2,52.0a1}`?

**Comment by seanmonstar** [comment]
My initial comment is just a distraction, since hapi does not validate errors by default (https://github.com/hapijs/hapi/blob/v14.2.0/lib/validation.js#L163), and this error is in validation.

Staring really hard at the problem, I cannot see the issue, but blowing up with 500s feels bad.

While I don't know the exact cause, there is an option we can set so that response validation never blows us up again: Setting `route.config.response.failAction` to `'log'`, it will log the errors, but still send the payload. Thoughts?

**Comment by philbooth** [comment]
If we can't reproduce locally, maybe we should add some special case logging for exactly this case then look for it to show up in our production logs.

**Comment by jrgm** [comment]
I've seen a UA of Win 10 Fx 51 reporting this same error, so it's something in Fx51+ that needs to be fixed before that is beta.

**Comment by jrgm** [comment]
> that needs to be fixed before that is beta.

By which I mean, if the root cause bug is in Fx, then fixing it after it reaches beta will become more difficult. And the number of 500's will increase significantly if it reaches beta.

**Comment by vladikoff** [comment]
> I've seen a UA of Win 10 Fx 51 reporting this same error,

@jrgm could you link or provide the value it was reporting? I don't think we can call this a "UA": `Firefox-Android-FxAccounts/51.0a2 (Firefox)`

**Comment by jrgm** [comment]
@vladikoff - https://kibana-fxa-us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/PROD%20-%20Auth%20HTTP%20Errors

**Comment by vladikoff** [comment]
Found the problem, if the request is sent to bad device id then it would throw a 500.

In the `to` field: https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#request-22
