### ISSUE TITLE
An error from db-server instead cause hapi validation errors that uid was missing from response

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1590]
The error from the db-server does not appear in the logs, so it is also eaten somewhere. If we want to deal with that separately, we can make a separate issue.

Here is the relevant log line:

```json
{
    "Timestamp": 1481582574987000000,
    "Logger": "fxa-auth-server",
    "Type": "request.summary",
    "Severity": 2,
    "Pid": 25262,
    "EnvVersion": "2.0",
    "Fields": {
        "op": "request.summary",
        "code": 500,
        "errno": 999,
        "rid": "1481582574980:ip-172-31-9-166:25262:ivo4etji:20017",
        "path": "/auth/v1/account/create",
        "lang": "en-US,en;q=0.5",
        "agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0",
        "remoteAddressChain": "[\"70.181.115.131\",\"172.31.13.228\",\"127.0.0.1\"]",
        "t": 7,
        "uid": "00",
        "service": "2651b9211a44b7b2",
        "email": "seantest12122016@mailinator.com",
        "stack": "Error: child \"uid\" fails because [\"uid\" is required]\n    at postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:201:26)\n    at _validateWithOptions (/data/fxa-auth-server/node_modules/joi/lib/any.js:604:20)\n    at root.validate (/data/fxa-auth-server/node_modules/joi/lib/index.js:105:23)\n at internals.input.exports.response.postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:221:20)\n    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)\n at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)\n at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16\n    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:86:16)\n at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n at internals.Response._prepare.internals.Response._processPrepare.next [as _processPrepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:521:16)\n    at internals.Response._prepare.next [as _prepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:460:21)\n    at /data/fxa-auth-server/node_modules/hapi/lib/reply.js:152:22\n    at nextTickCallbackWith0Args (node.js:420:9)\n    at process._tickDomainCallback (node.js:390:13)"
    }
}
```

**Comment by vladikoff** [comment]
Also getting the same on latest.dev

```
{"Timestamp":1481637377747000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":30783,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":500,"errno":999,"rid":"1481637377652:ip-172-31-6-64:30783:iwmqzjc3:11853","path":"/auth/v1/account/create","lang":"en-US,en;q=0.8,da;q=0.6","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36","remoteAddressChain":"[\"99.248.64.68\",\"172.31.29.121\",\"127.0.0.1\"]","t":95,"uid":"00","email":"a@restmail.net","stack":"Error: child \"uid\" fails because [\"uid\" is required]\n    at postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:201:26)\n    at _validateWithOptions (/data/fxa-auth-server/node_modules/joi/lib/any.js:604:20)\n    at root.validate (/data/fxa-auth-server/node_modules/joi/lib/index.js:105:23)\n    at internals.input.exports.response.postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:221:20)\n    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)\n    at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16\n    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:86:16)\n    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at internals.Response._prepare.internals.Response._processPrepare.next [as _processPrepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:521:16)\n    at internals.Response._prepare.next [as _prepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:460:21)\n    at /data/fxa-auth-server/node_modules/hapi/lib/reply.js:152:22\n    at nextTickCallbackWith0Args (node.js:436:9)\n    at process._tickDomainCallback (node.js:406:13)"}}
{"Timestamp":1481637380508000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":30783,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1481637380476:ip-172-31-6-64:30783:iwmqzjc3:11854","path":"/auth/v1/recovery_email/status","lang":"en-US,en;q=0.8,da;q=0.6","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36","remoteAddressChain":"[\"99.248.64.68\",\"172.31.11.74\",\"127.0.0.1\"]","t":32,"uid":"00"}}
```

cc @jrgm @jbuck

**Comment by rfk** [comment]
Here's what's happening AFAICT:

* The auth-db-server returns a HTTP 500 error response
* Our pool code rejects the promise with the response body [1] as a plain old object (i.e. *not* an instance off `Error`)
* This plain old old gets passed to the Hapi `reply` function at [1]
* Since it's not an instance of `Error`, Hapi treats it like a success response, trys to validate it against the response schema, and fails.

If I change pool.js to reject with an instance of `Error` then the proper error appears to be logged.  (And the client still sees a 500 response).

[1] https://github.com/mozilla/fxa-auth-server/blob/master/lib/pool.js#L56
[2] https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L118

**Comment by seanmonstar** [comment]
Rejecting with an instance of `Error` is definitely the correct approach.
