### ISSUE TITLE
remote db test failing locally

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1687]
```
~/c/fxa-auth-server (master) $ mocha test/remote/db_tests.js


  remote db
    ✓ ping
    ✓ account creation
    1) session token handling
    ✓ device registration
    ✓ keyfetch token handling
    ✓ reset token handling
    ✓ forgotpwd token handling
    ✓ email verification
    ✓ db.forgotPasswordVerified
    ✓ db.resetAccount
    ✓ db.securityEvent
    ✓ db.securityEvents
    ✓ unblock code
    ✓ account deletion


  13 passing (2s)
  1 failing

  1) remote db session token handling:

      AssertionError: 1488367004202 == 1488367004210 from assert.equal(sessionToken.lastAccessTime, sessionToken.createdAt)
      + expected - actual

      -1488367004202
      +1488367004210

      at Function.insist [as equal] (node_modules/insist/insist.js:93:19)
      at test/remote/db_tests.js:146:18
      at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
      at Async._drainQueue (node_modules/bluebird/js/main/async.js:128:12)
      at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)
```

Latest `master`, happens every time. Is nobody else seeing this?

**Comment by philbooth** [comment]
Oh, doesn't happen when you `npm t`. I guess that's fine then, lol.
