### ISSUE TITLE
/sms/status fails when running locally

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1747]
`request.app.clientAddress` is `127.0.0.1` so `fxa-geodb` returns an empty result. We then try to dereference `result.location.countryCode`, which fails with the error @shane-tomlinson reported in IRC:

```
Error: Unspecified error
    at Function.AppError.invalidRegion.AppError.messageRejected.AppError.unexpectedError (/Users/pb/code/fxa-auth-server/lib/error.js:555:10)
    at /Users/pb/code/fxa-auth-server/lib/routes/sms.js:116:27
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/promise.js:681:18)
    at Async._drainQueue (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/pb/code/fxa-auth-server/node_modules/fxa-geodb/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)"}
```

Fixing the dereference is obviously easy but is it definitely 100% safe to bypass the region check when `request.app.clientAddress === 127.0.0.1`?

**Comment by vladikoff** [comment]
Yay!
