### ISSUE TITLE
Mildly flaky remote test?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1789]
Noticed on 1 run of 4, locally, against the memory db, just now:

```
  706 passing (28s)
  1 failing

  1) mailer reminder db fetchReminders:

      AssertionError: fetched the created reminder from assert.ok(reminderFound, 'fetched the created reminder')
      + expected - actual

      -false
      +true

      at Function.insist [as ok] (node_modules/insist/insist.js:93:19)
      at test/remote/mailer_reminder_db_tests.js:86:18
      at tryCatch1 (node_modules/fxa-auth-db-mysql/node_modules/bluebird/js/main/util.js:43:21)
      at Promise$_callHandler [as _callHandler] (node_modules/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:627:13)
      at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (node_modules/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:641:18)
      at Promise$_settlePromiseAt [as _settlePromiseAt] (node_modules/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:800:14)
      at Promise$_settlePromises [as _settlePromises] (node_modules/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:934:14)
      at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (node_modules/fxa-auth-db-mysql/node_modules/bluebird/js/main/async.js:75:12)
      at Async$consumeFunctionBuffer (node_modules/fxa-auth-db-mysql/node_modules/bluebird/js/main/async.js:38:14)
```

**Comment by vladikoff** [comment]
Haven't seen this recently, please reopen if anyone can see this again
