### ISSUE TITLE
Add 'missing payload' to metricsContext errors

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1817]
Need a null check here for some reason. 
```
TypeError: Cannot read property 'metricsContext' of null",
"stack":"
    at validate [as validateMetricsContext] (/data/fxa-auth-server/lib/metrics/context.js:180:34)
    at emitRouteFlowEvent (/data/fxa-auth-server/lib/metrics/events.js:124:66)
    at Lug.summary (/data/fxa-auth-server/lib/log.js:103:11)
    at /data/fxa-auth-server/lib/server.js:320:11
    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:403:22
    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Function.wrapped [as _next] (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at Function.internals.Reply.interface.internals.continue (/data/fxa-auth-server/node_modules/hapi/lib/reply.js:108:10)
    at /data/fxa-auth-server/node_modules/hapi-hpkp/lib/hpkp.js:58:26
    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:403:22
    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:398:15
    at internals.Protect.run.finish [as run] (/data/fxa-auth-server/node_modules/hapi/lib/protect.js:56:16)
    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:396:19)
    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:455:10)
    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:389:21
    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:23:21)
    at request._protect.run (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:110:20)
    at _validateWithOptions (/data/fxa-auth-server/node_modules/joi/lib/any.js:604:20)
    at root.validate (/data/fxa-auth-server/node_modules/joi/lib/index.js:105:23)
    at Object.internals.input.postValidate [as input] (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:137:20)
    at exports.payload (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:42:22)
    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)
    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at request._protect.run (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:68:20)
```

**Comment by jrgm** [comment]
https://github.com/mozilla/fxa-auth-server/pull/1820/files checked this. But I think that we might want to track/debug `!this.payload` separately, since this just started happening.

**Comment by vladikoff** [comment]
@jrgm true! I guess the difference you would get `'missing context'` vs `missing payload`
