### ISSUE TITLE
npm test fails generating keypair

### ISSUE THREAD

**Issue by MrHappy** [mozilla/fxa-auth-server#1827]
Running on Ubuntu 14.04
`
> fxa-auth-server@1.84.2 test /opt/fxa-auth-server
> NODE_ENV=dev CORS_ORIGIN=http://foo,http://bar scripts/test-local.sh

Generating keypair
undefined:1

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /opt/fxa-auth-server/scripts/gen_keys.js:64:18
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
npm ERR! Test failed.  See above for more details.
`

**Comment by MrHappy** [comment]
appears to be wrong nodejs/npm version, reverted back to node 4.8 and it's fine
