### ISSUE TITLE
if not features.isSecondaryEmailEnabled(), auth-server hits exception

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1871]
I was working on the dockerflow stage auth-server, and running tests, but hadn't updated the config to set `secondaryEmail.enabled` to `true`. It was dumping this stack.

So, we can't disable this feature gracefully. 

Maybe want to change the return here: https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L514-L520

```
"stack":"TypeError: Cannot read property 'then' of undefined
    at /app/lib/routes/account.js:559:21
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)"}}
```

**Comment by vladikoff** [comment]
@jrgm we have to fix this. However do not enable this feature yet in general.
