### ISSUE TITLE
Possible flaky test for additional emails when running against mysql db?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1963]
@vbudhram, maybe this isn't a problem or maybe I'm doing something wrong, raising it just in case.

When I ran train-89 auth server tests against train-89 mysql-db I got an error:

```
  ․․․․․․․․․․․․․․․․․!․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  825 passing (1m)
  1 failing

  1) remote emails should receive emails on verified secondary emails receives password reset notification:

      AssertionError: returns correct email from assert.equal(res[1].email, secondEmail, 'returns correct email')
      + expected - actual

      -04334e2cb11e65332028@restmail.net
      +5202b37e9239c9de87e1@restmail.net
      
      at Function.insist [as equal] (node_modules/insist/insist.js:93:19)
      at client.forgotPassword.then.then.then.then.then.then.then (test/remote/recovery_email_emails.js:604:20)
      at bound (domain.js:280:14)
      at runBound (domain.js:293:12)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

I ran them again and it went away. Problem or nothing to worry about?

Looks like it might be a non-deterministic recordset ordering kind of thang?

**Comment by philbooth** [comment]
Also seen this one?

```
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  825 passing (1m)
  1 failing

  1) remote emails should create and get additional email can create:
     AssertionError: { [AssertionError: returns correct email from assert.equal(res[2].email, thirdEmail, 'returns correct email')]
  name: 'Assertio undefined undefined

      at test/remote/recovery_email_emails.js:85:20
      at bound (domain.js:287:14)
      at runBound (domain.js:300:12)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:687:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by vbudhram** [comment]
I've seen this before and it very well could be timing issue.

**Comment by philbooth** [comment]
Fwiw I haven't seen this in the last week or so, closing.
