### ISSUE TITLE
[train-91] TypeError: d.id.equals is not a function at devicesToNotify.filter.d

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2005]
train-91 was showing these 500 errors, on route /v1/password/change/finish for ~90% or attempts. (Looked like 100% early on, but a couple have succeeded).

I see this very line was changed in master: https://github.com/mozilla/fxa-auth-server/pull/1983/files#diff-4569118cb0662d8d36730e0b25bd4571L199, so this may already be (mostly) fixed and just needs to be backported to a v1.91.3 tag.

I have rolled back train-91, after chatting with @rfk 

/cc @vbudhram, @rfk, @jbuck 

```
TypeError: d.id.equals is not a function 
at devicesToNotify.filter.d (/app/lib/routes/password.js:199:72) 
at Array.filter (native) at /app/lib/routes/password.js:199:53 
at bound (domain.js:280:14) at runBound (domain.js:293:12) 
at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31) at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18) 
at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10) 
at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:691:18) 
at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16) 
at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10) 
at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14) 
at runCallback (timers.js:672:20) 
at tryOnImmediate (timers.js:645:5) 
at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by jrgm** [comment]
Bah. Line breaks. Fixing.

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-auth-server/issues/2006 

@vbudhram @jrgm do we need a point release?

**Comment by jrgm** [comment]
> @vbudhram @jrgm do we need a point release?

@vbudhram already did a v1.91.3 tag after merging to train-91, which I am about to make live.

**Comment by vladikoff** [comment]
👍
