### ISSUE TITLE
steady postValidate 500 in /v1/account/device with train-97

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2171]
Since about an hour after Thursday release of train-97:

Error: child "type" fails because ["type" must be a string]
    at postValidate (/app/node_modules/hapi/lib/validation.js:211:30)
    at _validateWithOptions (/app/node_modules/joi/lib/any.js:604:20)
    at root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:121:23)
    at exports.response (/app/node_modules/hapi/lib/validation.js:241:20)
    at each (/app/node_modules/hapi/lib/request.js:413:16)
    at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/app/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at finalize (/app/node_modules/hapi/lib/handler.js:23:16)
    at Hoek.once (/app/node_modules/hapi/lib/protect.js:50:16)
    at wrapped (/app/node_modules/hapi/node_modules/hoek/lib/index.js:875:20)
    at finalize (/app/node_modules/hapi/lib/handler.js:91:16)
    at wrapped (/app/node_modules/hapi/node_modules/hoek/lib/index.js:875:20)
    at internals.Response._processPrepare (/app/node_modules/hapi/lib/response.js:546:16)
    at internals.Response._prepare (/app/node_modules/hapi/lib/response.js:474:21)
    at process.nextTick (/app/node_modules/hapi/lib/reply.js:183:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by rfk** [comment]
And here in sentry: https://sentry.prod.mozaws.net/operations/auth-prod/issues/668478/

If I had to guess, I suspect https://github.com/mozilla/fxa-auth-server/pull/2132 and some devices that don't have a `type` property, causing us to return `type: null` or similar in the response where previous we would not have emitted a `type` key at all.

**Comment by jrgm** [comment]
Fixed in https://github.com/mozilla/fxa-auth-server/pull/2172 and now in production. 5xx gone.
