### ISSUE TITLE
Internal Error when starting the server

### ISSUE THREAD

**Issue by vigri** [mozilla/fxa-auth-server#2202]
I would like to report a problem with the fx-auth-server.

**System:**
Synology NAS 214+, ARM CPU

**Problem:**
When trying to starting the server or running npm test I get the following error:

```
npm test
> fxa-auth-server@1.99.0 test /volume1/services/fxa-auth-server
> NODE_ENV=dev CORS_ORIGIN=http://foo,http://bar VERIFIER_VERSION=0 MEMCACHE_METRICS_CONTEXT_ADDRESS=none NO_COVERAGE=1 scripts/test-local.sh

keys file already exists

/volume1/services/fxa-auth-server/node_modules/scrypt-hash/node_modules/bindings/bindings.js:83
        throw e
        ^
Error: /volume1/services/fxa-auth-server/node_modules/scrypt-hash/build/Release/scrypt.node: internal error
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/volume1/services/fxa-auth-server/node_modules/scrypt-hash/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/volume1/services/fxa-auth-server/node_modules/scrypt-hash/index.js:1:97)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/volume1/services/fxa-auth-server/lib/crypto/scrypt.js:8:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/volume1/services/fxa-auth-server/test/local/crypto/scrypt.js:15:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /volume1/services/fxa-auth-server/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/volume1/services/fxa-auth-server/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/volume1/services/fxa-auth-server/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/volume1/services/fxa-auth-server/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! Test failed.  See above for more details.
```

Executing **npm rebuild** results in no errors.

Please let me know if you need any further information.

**Comment by vladikoff** [comment]
I think because of the ARM cpu it will not work. the scrypt library might not support that

**Comment by vigri** [comment]
I've executed objdump on scrypt.node

`x1@nas:/volume1/services/fxa-auth-server/node_modules/scrypt-hash/build/Release$ objdump -f scrypt.node
scrypt.node:     file format elf32-littlearm
architecture: arm, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00001a78`

**Comment by vbudhram** [comment]
from mtg: closing for now until we can prioritize
