### ISSUE TITLE
Persistent intermittent test failure in CI

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2276]
In the last few days I've started seeing an intermittent failure in CI with about 75-ish% regularity.

```
1278 passing (2m)
1 failing
1) /account/login sign-in confirmation skip for new accounts don't skip sign-in confirmation on older account:
   AssertionError [ERR_ASSERTION]: sessionToken was created unverified from assert.ok(tokenData.tokenVerificationId, 'sessionToken was created unverified')
    at Function.insist [as ok] (node_modules/insist/insist.js:93:19)
    at test/local/routes/account.js:944:18
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by philbooth** [comment]
And it seems like the failures are always in node 8 too fwiw. I'll try testing in node 8 to reproduce locally.

**Comment by philbooth** [comment]
Fwiw, I've been trying this locally, haven't managed to so far.

**Comment by philbooth** [comment]
This stopped happening at some point. :tada:
