### ISSUE TITLE
Sporadic test failure: "Vapid private key should be 32 bytes long when decoded"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2406]
We seem to get failures like [this](https://travis-ci.org/mozilla/fxa-auth-server/jobs/369274253) pretty regularly:

```
> fxa-auth-server@1.110.1 test-e2e /home/travis/build/mozilla/fxa-auth-server
> NODE_ENV=dev mocha test/e2e
  e2e/push
    1) notifyUpdate sends notifications using a real push server
  0 passing (449ms)
  1 failing
  1) e2e/push notifyUpdate sends notifications using a real push server:
     Error: Vapid private key should be 32 bytes long when decoded.
      at validatePrivateKey (node_modules/web-push/src/vapid-helper.js:88:11)
      at Object.getVapidHeaders (node_modules/web-push/src/vapid-helper.js:121:3)
      at Object.WebPushLib.sendNotification (node_modules/web-push/src/web-push-lib.js:195:40)
      at lib/push.js:462:26
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (node_modules/bluebird/js/release/reduce.js:155:18)
      at Object.gotAccum (node_modules/bluebird/js/release/reduce.js:144:25)
      at Object.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromiseCtx (node_modules/bluebird/js/release/promise.js:604:10)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:12)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

It's probably some jank when randomly generating VAPID keys, e.g. stripping leading zero.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-auth-server/issues/1816#issuecomment-301603161 O_o

**Comment by vladikoff** [comment]
(seems like this only happens in Aprils, so we just wait until the month is over?)

**Comment by rfk** [comment]
That's the one.  I'm able to repro using only code from the underlying web-push library, so I think it's probably an upstream bug.

**Comment by rfk** [comment]
Looks like it's fixed in latest upstream release: https://github.com/web-push-libs/web-push/issues/295
