### ISSUE TITLE
Intermittent exception running tests locally

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2476]
> Unhandled rejection Error: blee
    at Context.it (/Users/shanetomlinson/development/fxa-auth-server/test/local/metrics/context.js:572:30)
    at callFn (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runnable.js:343:21)
    at Test.Runnable.run (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runnable.js:335:7)
    at Runner.runTest (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:444:10)
    at /Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:550:12
    at next (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:361:14)
    at /Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:295:14)
    at /Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:334:7
    at done (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runnable.js:293:5)
    at callFn (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runnable.js:361:7)
    at Hook.Runnable.run (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runnable.js:335:7)
    at next (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/shanetomlinson/development/fxa-auth-server/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by vladikoff** [comment]
from mtg: timing issue?

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-auth-server/issues/2534
