### ISSUE TITLE
train-114: Error: "capabilities" is not allowed

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2477]
```
"path":"/v1/account/device"

Error: "capabilities" is not allowed
    at postValidate (/app/node_modules/hapi/lib/validation.js:214:30)
    at internals.Object._validateWithOptions (/app/node_modules/joi/lib/types/any/index.js:672:20)
    at module.exports.internals.Any.root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:139:23)
    at exports.response (/app/node_modules/hapi/lib/validation.js:244:20)
    at each (/app/node_modules/hapi/lib/request.js:401:16)
    at iterate (/app/node_modules/items/lib/index.js:36:13)
    at done (/app/node_modules/items/lib/index.js:28:25)
    at finalize (/app/node_modules/hapi/lib/handler.js:23:16)
    at Hoek.once (/app/node_modules/hapi/lib/protect.js:50:16)
    at wrapped (/app/node_modules/hoek/lib/index.js:879:20)
    at finalize (/app/node_modules/hapi/lib/handler.js:91:16)
    at wrapped (/app/node_modules/hoek/lib/index.js:879:20)
    at module.exports.internals.Response.internals.Response._processPrepare (/app/node_modules/hapi/lib/response.js:548:16)
    at module.exports.internals.Response.internals.Response._prepare (/app/node_modules/hapi/lib/response.js:476:21)
    at process.nextTick (/app/node_modules/hapi/lib/reply.js:183:22)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"}}

```

**Comment by rfk** [comment]
Hrm, we allow a zero-length capabilities array here:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/devices-and-sessions.js#L129

But perhaps there are a small number of devices that are sending a non-empty array.

**Comment by jrgm** [comment]
Actually, I was wondering the same, and put one instance of 114 back in just long enough to ngrep the request/response for one error on /account/device.

They request payload was:
```
{
  "id":"...",
  "name":"...",
  "pushCallback":"...",
  "pushPublicKey":"...",
  "pushAuthKey":"...",
  "capabilities":[]
}
```
and that resulted in a 500 response.

It doesn't mean that there aren't cases where the array in non-empty, but in this one case, it was not empty.

**Comment by rfk** [comment]
>  at module.exports.internals.Response.internals.Response._processPrepare (/app/node_modules/hapi/lib/response.js:548:16)

Oooh, it's erroring because we're including a "capabilities" field in the response, and response validation does not allow it.  I'll see about a patch shortly.
