### ISSUE TITLE
Intermittent timeout in totp test

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2534]
Got this 3 times out of 4 in circle just now:

```
1609 passing (8m)
1 failing

1) remote totp "before each" hook for "should request `totp-2fa` on login if user has verified totp token":
   Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by vladikoff** [comment]
also seeing

 1) remote recovery keys "before each" hook for "should get recovery key": An internal server error occurred

**Comment by vbudhram** [comment]
@vladikoff was `should get recovery key` test also in circle?

**Comment by vladikoff** [comment]
@vbudhram i think i saw it in circle, but @brizental saw it locally

**Comment by vbudhram** [comment]
Seen this in https://github.com/mozilla/fxa-auth-server/pull/2529
```
  1628 passing (2m)
  1 failing
  1) remote db reset token handling:
     AssertionError [ERR_ASSERTION]: accountResetToken() fails with the correct error code from assert.equal(err.errno, 110, 'accountResetToken() fails with the correct error code')
```

**Comment by shane-tomlinson** [comment]
In https://circleci.com/gh/mozilla/fxa-auth-server/3050:

"remote totp "before each" hook for "should verify totp code from previous code window": An internal server error occurred"

**Comment by vbudhram** [comment]
A new one
```
  1667 passing (8m)
  1 failing

  1) remote signinCodes POST /signinCodes/consume valid code:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by vladikoff** [comment]
@vbudhram was this fixed with timeout updates?

**Comment by philbooth** [comment]
Got these two in Circle just now:

```
  1730 passing (7m)
  2 failing

  1) remote session
       reauth
         updates the last-auth time:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/test/remote/session_tests.js)
  

  2) remote totp
       "before each" hook for "should check if totp token exists for user":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/test/remote/totp_tests.js)
```

**Comment by vbudhram** [comment]
Got these 

```
 1459 passing (39s)
  1 failing
  1) lib/senders/oauth_client_info:
       fetch:
         fetches and memory caches client information:
AssertionError: expected 'fetch.usedServer' to equal 'fetch.usedCache'
+ expected- actual
-fetch.usedServer
+fetch.usedCache
      at fetch.then.then (test/local/senders/oauth_client_info.js:121:16)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```
