### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by rektboi** [mozilla/fxa-auth-server#2561]
So I got some error running as root, created a user, install, run then I got this. No idea how to proceed. Thx. 

> fxa-auth-server@1.116.0 start /home/fxa-auth-server
> NODE_ENV=dev scripts/start-local.sh 2>&1

Generating keypair
Secret Key saved: /home/fxa-auth-server/config/secret-key.json
Public Key saved: /home/fxa-auth-server/config/public-key.json
Generating key for VAPID
Done: /home/fxa-auth-server/config/vapid-keys.json
Local SMTP server listening on port 9999
mail_helper started...
{"Timestamp":1533190740532000000,"Logger":"fxa-auth-db-server","Type":"uncaughtException","Severity":0,"Pid":9700,"EnvVersion":"2.0","Fields":{"error":"Error: Could not locate the bindings file. Tried:\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/Debug/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/Release/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/out/Debug/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/Debug/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/out/Release/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/Release/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/default/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/compiled/10.6.0/linux/x64/scrypt.node","stack":"\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/Debug/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/Release/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/out/Debug/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/Debug/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/out/Release/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/Release/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/build/default/scrypt.node\n → /home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/compiled/10.6.0/linux/x64/scrypt.node\n    at bindings (/home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/bindings/bindings.js:88:9)\n    at Object.<anonymous> (/home/fxa-auth-server/node_modules/fxa-auth-db-mysql/node_modules/scrypt-hash/index.js:1:97)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/fxa-auth-server/node_modules/fxa-auth-db-mysql/lib/db/util.js:10:32)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)"}}
fxa-auth-server.CRITICAL: uncaughtException Error: ENOENT: no such file or directory, open '/home/fxa-auth-server/node_modules/fxa-geodb/db/cities-db.mmdb'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.exports.openSync (/home/fxa-auth-server/node_modules/maxmind/index.js:49:30)
    at module.exports (/home/fxa-auth-server/node_modules/fxa-geodb/lib/fxa-geodb.js:16:28)
    at Object.<anonymous> (/home/fxa-auth-server/lib/geodb.js:8:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at run (/home/fxa-auth-server/bin/key_server.js:18:20)
    at main (/home/fxa-auth-server/bin/key_server.js:160:3)
    at Object.<anonymous> (/home/fxa-auth-server/bin/key_server.js:184:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fxa-auth-server@1.116.0 start: `NODE_ENV=dev scripts/start-local.sh 2>&1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa-auth-server@1.116.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fxa/.npm/_logs/2018-08-02T06_19_00_638Z-debug.log
fxa@phoenix:/home/fxa-auth-server$ more /home/fxa/.npm/_logs/2018-08-02T06_19_00_638Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fxa-auth-server@1.116.0~prestart: fxa-auth-server@1.116.0
6 info lifecycle fxa-auth-server@1.116.0~start: fxa-auth-server@1.116.0
7 verbose lifecycle fxa-auth-server@1.116.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle fxa-auth-server@1.116.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/n
pm-lifecycle/node-gyp-bin:/home/fxa-auth-server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/s
bin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle fxa-auth-server@1.116.0~start: CWD: /home/fxa-auth-server
10 silly lifecycle fxa-auth-server@1.116.0~start: Args: [ '-c', 'NODE_ENV=dev scripts/start-local.sh 2>
&1' ]
11 silly lifecycle fxa-auth-server@1.116.0~start: Returned: code: 1  signal: null
12 info lifecycle fxa-auth-server@1.116.0~start: Failed to exec start script
13 verbose stack Error: fxa-auth-server@1.116.0 start: `NODE_ENV=dev scripts/start-local.sh 2>&1`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-life
cycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-life
cycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid fxa-auth-server@1.116.0
15 verbose cwd /home/fxa-auth-server
16 verbose Linux 4.4.0-130-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.6.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error fxa-auth-server@1.116.0 start: `NODE_ENV=dev scripts/start-local.sh 2>&1`
22 error Exit status 1
23 error Failed at the fxa-auth-server@1.116.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shane-tomlinson** [comment]
@rektboi - I see you are using node 10, can you retry with node 8x and see if the problem still occurs?
