### ISSUE TITLE
Failing locally: test/local/senders/oauth_client_info.js

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2579]
This just happened 1 time out of 4 locally, never seen it fail before:

```
  1724 passing (3m)
  1 failing

  1) lib/senders/oauth_client_info: fetch: fetches and memory caches client information:

      AssertionError [ERR_ASSERTION]: 'fetch.usedServer' == 'fetch.usedCache' from assert.equal(mockLog.trace.getCall(3).args[0].op, 'fetch.usedCache')
      + expected - actual

      -fetch.usedServer
      +fetch.usedCache

      at fetch.then.then (test/local/senders/oauth_client_info.js:121:16)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by philbooth** [comment]
No, haven't seen it since I opened it I don't think, feel free to close.

**Comment by vladikoff** [comment]
closing for now!
