### ISSUE TITLE
[train-120] tests failing on geodb expectations

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2609]
e.g., https://circleci.com/gh/mozilla/fxa-auth-server/3288

1) geodb
       returns location data when enabled:

      AssertionError: expected 'Oakland' to equal 'Mountain View'
      + expected - actual

      -Oakland
      +Mountain View
      
      at Context.it (test/local/geodb.js:31:14)

  2) lib/server
       set up mocks:
         create:
           server.start:
             successful request, authenticated, acceptable locale, signinCodes feature enabled:
               parsed location correctly:

      AssertionError: expected 'Oakland' to equal 'Mountain View'
      + expected - actual

      -Oakland
      +Mountain View
      
      at Context.it (test/local/server.js:195:20)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  3) lib/server
       set up mocks:
         create:
           server.start:
             successful request, authenticated, acceptable locale, signinCodes feature enabled:
               successful request, unauthenticated, uid in payload:
                 second request has its own location info:

      AssertionError: expected 'Oakland' to equal 'Mountain View'
      + expected - actual

      -Oakland
      +Mountain View
      
      at Context.it (test/local/server.js:272:22)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  4) remote totp
       "before each" hook for "should check if totp token exists for user":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/test/remote/totp_tests.js)

**Comment by vladikoff** [comment]
@jrgm but not the CI version?

**Comment by jrgm** [comment]
`npm run test-ci` works for me locally (for test/local). [I can never get the remote tests to run.]

Also, there's an unhandledRejection in there:
```
Unhandled rejection Error: blee
    at Context.it (/app/test/local/metrics/context.js:572:30)
    at callFn (/app/node_modules/mocha/lib/runnable.js:372:21)
    at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:364:7)
    at Runner.runTest (/app/node_modules/mocha/lib/runner.js:455:10)
    at /app/node_modules/mocha/lib/runner.js:573:12
    at next (/app/node_modules/mocha/lib/runner.js:369:14)
    at /app/node_modules/mocha/lib/runner.js:379:7
    at next (/app/node_modules/mocha/lib/runner.js:303:14)
    at /app/node_modules/mocha/lib/runner.js:342:7
    at done (/app/node_modules/mocha/lib/runnable.js:319:5)
    at callFn (/app/node_modules/mocha/lib/runnable.js:395:7)
    at Hook.Runnable.run (/app/node_modules/mocha/lib/runnable.js:364:7)
    at next (/app/node_modules/mocha/lib/runner.js:317:10)
    at Immediate.<anonymous> (/app/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by shane-tomlinson** [comment]
@jrgm, @vladikoff - was this fixed with the "Mountain View" => "Oakland" transformation?

**Comment by shane-tomlinson** [comment]
Closing as fixed.
