### ISSUE TITLE
fxa-oauth-server.db.ERROR: client.missing.keys {"key":"imageUri","name":"Android Components Reference Browser"}

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2726]
I was starting locally with `./bin/purge-expired-tokens.js` and got this error, which is related to https://github.com/mozilla/fxa-auth-server/commit/d11afc0685c72e1cb5b89e49403109c14e5c19a1. Can just add the imageUri to workaround, or relax this restriction.

```
fxa-oauth-server.db.ERROR: client.missing.keys {"key":"imageUri","name":"Android Components Reference Browser"}
fxa-oauth-server.db.ERROR: ping Error: Client config has missing keys
    at /Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/lib/db/index.js:72:17
    at Array.forEach (<anonymous>)
    at /Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/lib/db/index.js:68:29
    at Array.map (<anonymous>)
    at preClients (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/lib/db/index.js:53:26)
    at exports._initialClients (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/lib/db/index.js:213:10)
    at tryCatcher (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/jrgm/gitwork/fxa-auth-server/fxa-oauth-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
```

**Comment by rfk** [comment]
> Can just add the imageUri to workaround

I'll make a quick PR that does this.
