### ISSUE TITLE
Persistent travis failure in e2e/push

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2737]
I retried this job three times but it failed on all three:

  https://travis-ci.org/mozilla/fxa-auth-server/jobs/454370197

The relevant part of the log is:

```
0.89s$ npm run test-e2e
> fxa-auth-server@1.124.3 test-e2e /home/travis/build/mozilla/fxa-auth-server
> NODE_ENV=dev mocha test/e2e
  e2e/push
    1) sendPush sends notifications using a real push server
  0 passing (230ms)
  1 failing
  1) e2e/push
       sendPush sends notifications using a real push server:
     Error: Error: socket hang upundefined
      at WebSocket.error (test/push_helper.js:84:13)
      at ClientRequest.req.on (node_modules/ws/lib/websocket.js:535:10)
      at TLSSocket.socketOnEnd (_http_client.js:423:9)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)
```

I wonder if this is some early indication of a change/problem in our integration with the push infrastructure.

**Comment by rfk** [comment]
I can repro locally with `npm run test-e2e`

**Comment by rfk** [comment]
I occasionally get:

```
  e2e/push                                                                                                                                           1) sendPush sends notifications using a real push server                                                                                                                                                                                                                                                                                                                                                                                         0 passing (2s)                                                                                                                                   1 failing                                                                                                                                                                                                                                                                                         1) e2e/push                                                                                                                                           sendPush sends notifications using a real push server:                                                                                         Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/rfk/repos/mozilla/fxa-auth-server/test/e2e/push_tests.js)           
```

If I bump the test runner timeout to 2000 to 10000 then I can get it to *sporadically* pass, maybe one in every four or five attempts.  The other attempts fail with a socket hangup.

So I wonder if this reflects an issue with the push service websocket infrastructure..?

**Comment by rfk** [comment]
Even just doing this from a JS console:

```
s = new WebSocket("wss://push.services.mozilla.com/"); s.onopen = () => console.log("OK!"); s.onerror = () => console.log("ERROR!")
```

Seems to alternate between erroring, or connecting after a couple of seconds timeout.

**Comment by rfk** [comment]
Confirmed in IRC that push is indeed experiencing some operational issue; leaving the bug open for now to confirm when it's resolved.

**Comment by rfk** [comment]
Push is back up and running, and the job restarted successfully.
