### ISSUE TITLE
Docs script is failing in master

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2759]
```
TypeError: Error parsing "lib/error.js" at line 751:
Expected type [Literal,MemberExpression,BinaryExpression,LogicalExpression], found "Identifier" at column "4"
  at fail (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/scripts/write-api-docs.js:155:9)
  at assertType (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/scripts/write-api-docs.js:398:5)
  at findProperty (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/scripts/write-api-docs.js:474:5)
  at marshallErrorProperty (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/scripts/write-api-docs.js:1005:20)
  at returns.forEach.r (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/scripts/write-api-docs.js:934:14)
  at Array.forEach (<anonymous>:null:null)
  at marshallErrors (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/scripts/write-api-docs.js:928:11)
  at Array.reduce (<anonymous>:null:null)
  at parseModule.then.node (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/scripts/write-api-docs.js:877:10)
  at tryCatcher (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:512:31)
  at Promise._settlePromise (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:638:18)
  at Promise._resolveCallback (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:432:57)
  at Promise._settlePromiseFromHandler (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:524:17)
  at Promise._settlePromise (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/promise.js:638:18)
  at /Users/philbooth/code/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/release/nodeback.js:42:21
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by vladikoff** [comment]
@philbooth the error i was getting is the same, on onde v8.11

**Comment by philbooth** [comment]
Looks like this got fixed at some point.
